[project]
name = "mystocks-data-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "recoma", email = "seokbong60@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.63",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "types-boto3[essential]>=1.43.63",
]

[project.scripts]
exec-dev = "mystocks_data_collector:main"
test = "pytest:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-dotenv>=1.2.2",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
